<?php
/**
 * IA Power — Oficina Agéntica EdTech
 * config.php — RELLENAR CON DATOS REALES antes de subir a Dinahosting.
 * Este archivo NO debe contener placeholders en producción.
 */

return [
    'google_form_url' => 'https://docs.google.com/forms/d/e/FORM_ID/formResponse',
    'calendar_url'    => 'https://calendar.google.com/',
    'google_form_url' => 'https://docs.google.com/forms/d/e/1FAIpQLSdQcczpr6_2XzPNHvtM_1s7ASPuIN4YoeLX6NcWoWXqUncmdg/formResponse',
    'debug'           => false,
    'allow_insecure_ssl' => false,
    'rate_limit_enabled' => true,

    'entries' => [
        'nombre'             => 'entry.xxxxxxxxxx',
        'email'              => 'entry.xxxxxxxxxx',
        'telefono'           => 'entry.xxxxxxxxxx',
        'empresa'            => 'entry.xxxxxxxxxx',
        'cargo'              => 'entry.xxxxxxxxxx',
        'web'                => 'entry.xxxxxxxxxx',
        'tipo_organizacion'  => 'entry.xxxxxxxxxx',
        'tamano_equipo'      => 'entry.xxxxxxxxxx',
        'google_workspace'   => 'entry.xxxxxxxxxx',
        'area_prioritaria'   => 'entry.xxxxxxxxxx',
        'herramientas'       => 'entry.xxxxxxxxxx',
        'mensaje'            => 'entry.xxxxxxxxxx',
        'rgpd'               => 'entry.xxxxxxxxxx',
        'utm_source'         => 'entry.xxxxxxxxxx',
        'utm_medium'         => 'entry.xxxxxxxxxx',
        'utm_campaign'       => 'entry.xxxxxxxxxx',
        'utm_content'        => 'entry.xxxxxxxxxx',
        'utm_term'           => 'entry.xxxxxxxxxx',
        'ip'                 => 'entry.xxxxxxxxxx',
        'user_agent'         => 'entry.xxxxxxxxxx',
        'lead_score'         => 'entry.xxxxxxxxxx',
        'lead_status'        => 'entry.xxxxxxxxxx',
        'nombre'             => 'entry.1269787648',
        'email'              => 'entry.1968449715',
        'telefono'           => 'entry.786257083',
        'empresa'            => 'entry.815019934',
        'cargo'              => 'entry.2019105249',
        'web'                => 'entry.1771754867',
        'tipo_organizacion'  => 'entry.1399739765',
        'tamano_equipo'      => 'entry.1697056363',
        'google_workspace'   => 'entry.185368466',
        'area_prioritaria'   => 'entry.914965633',
        'herramientas'       => 'entry.1171977959',
        'mensaje'            => 'entry.100914184',
        'rgpd'               => 'entry.1586594448',
        'utm_source'         => 'entry.1536730311',
        'utm_medium'         => 'entry.176341995',
        'utm_campaign'       => 'entry.850685173',
        'utm_content'        => 'entry.1810965489',
        'utm_term'           => 'entry.1998477766',
        'ip'                 => 'entry.962945393',
        'user_agent'         => 'entry.728175204',
        'lead_score'         => 'entry.1153161696',
        'lead_status'        => 'entry.427778012',
    ],
];
